@startuml

package "Client Interface" {
  [Query Number]
}
 
node "Python Process" {
  CommandLine - [Query Processing]
  [Query Number] --> CommandLine

} 

node "Migration Python Process" {
  [Running restore.sql] --> [Query all records]
  [Query all records] --> [Adding all records]


} 

database "MongoDB" {
  frame "Collections NoSQL" {
	[Collections (Current DB Snapshot)]
  }
}

database "Postgres" {
  frame "Tables SQL" {
	  [Tables (Current DB Snapshot) ]
  }
}


[Query Processing] --> [Collections (Current DB Snapshot)]
[Running restore.sql] --> [Tables (Current DB Snapshot) ]
[Query all records] --> [Tables (Current DB Snapshot) ]
[Adding all records] --> [Collections (Current DB Snapshot)]


@enduml
